[placeholder]
name = "Wildflowers"
description = "Wildflowers along Tolmie Peak Trail near Mt. Rainier."

[placeholder-2]
name = "Hydrangea Blossoms"
description = "A close-up of hydrangea blossoms in the Washington Park Arboretum. Photographed April 2023."
